// AUTO-GENERATED by scripts/gen-translation-index.mjs — do not edit by hand.

import type {
  CardTranslation,
  ContentTranslation,
  TranslationKind,
} from "@/lib/content/translated";

/**
 * Which locales each slug has a translated body for.
 *
 * Read synchronously while metadata is generated, so a page can advertise
 * hreflang only for the languages it actually exists in.
 */
export const TRANSLATED: Record<TranslationKind, Record<string, string[]>> = {
  "blog": {
    "affordability-migration-west": [
      "te",
      "hi"
    ],
    "agricultural-vs-residential-land": [
      "te",
      "hi"
    ],
    "airport-connectivity-west": [
      "te",
      "hi"
    ],
    "best-investment-locations-hyderabad": [
      "te",
      "hi"
    ],
    "building-villa-on-plot": [
      "te",
      "hi"
    ],
    "capital-gains-tax-land": [
      "te",
      "hi"
    ],
    "chevella-moinabad-belt": [
      "te",
      "hi"
    ],
    "clubhouse-lifestyle": [
      "te",
      "hi"
    ],
    "construction-cost-planning": [
      "te",
      "hi"
    ],
    "down-payment-planning": [
      "te",
      "hi"
    ],
    "east-vs-west-hyderabad": [
      "te",
      "hi"
    ],
    "encumbrance-certificate-guide": [
      "te",
      "hi"
    ],
    "financial-district-spillover": [
      "te",
      "hi"
    ],
    "first-time-plot-buyer": [
      "te",
      "hi"
    ],
    "future-city-vision": [
      "te",
      "hi"
    ],
    "future-of-hyderabad-west": [
      "te",
      "hi"
    ],
    "gated-community-living": [
      "te",
      "hi"
    ],
    "gst-real-estate": [
      "te",
      "hi"
    ],
    "hmda-vs-dtcp": [
      "te",
      "hi"
    ],
    "hyderabad-real-estate-trends": [
      "te",
      "hi"
    ],
    "hyderabad-vs-bangalore-realty": [
      "te",
      "hi"
    ],
    "hyderabad-west-schools": [
      "te",
      "hi"
    ],
    "iit-hyderabad-kandi-effect": [
      "te",
      "hi"
    ],
    "industrial-corridors-hyderabad": [
      "te",
      "hi"
    ],
    "infrastructure-projects-hyderabad": [
      "te",
      "hi"
    ],
    "it-sector-hyderabad-realty": [
      "te",
      "hi"
    ],
    "joint-family-property-investment": [
      "te",
      "hi"
    ],
    "kokapet-neopolis-effect": [
      "te",
      "hi"
    ],
    "land-appreciation-hyderabad-west": [
      "te",
      "hi"
    ],
    "land-banking-strategy": [
      "te",
      "hi"
    ],
    "land-price-drivers": [
      "te",
      "hi"
    ],
    "luxury-living-west-hyderabad": [
      "te",
      "hi"
    ],
    "market-cycles-land": [
      "te",
      "hi"
    ],
    "metro-expansion-west": [
      "te",
      "hi"
    ],
    "mmts-shankarpally-connectivity": [
      "te",
      "hi"
    ],
    "mokila-villa-corridor": [
      "te",
      "hi"
    ],
    "negotiating-plot-purchase": [
      "te",
      "hi"
    ],
    "nri-guide-plot-investment": [
      "te",
      "hi"
    ],
    "orr-exit3-corridor": [
      "te",
      "hi"
    ],
    "orr-growth-story": [
      "te",
      "hi"
    ],
    "patancheru-industrial-corridor": [
      "te",
      "hi"
    ],
    "plot-buying-mistakes-stories": [
      "te",
      "hi"
    ],
    "plot-loan-vs-home-loan": [
      "te",
      "hi"
    ],
    "plots-vs-apartments": [
      "te",
      "hi"
    ],
    "plotted-development-boom": [
      "te",
      "hi"
    ],
    "portfolio-diversification-real-estate": [
      "te",
      "hi"
    ],
    "property-mutation-telangana": [
      "te",
      "hi"
    ],
    "reading-layout-plans": [
      "te",
      "hi"
    ],
    "real-estate-vs-gold-vs-equity": [
      "te",
      "hi"
    ],
    "regional-ring-road-progress": [
      "te",
      "hi"
    ],
    "rental-yield-vs-appreciation": [
      "te",
      "hi"
    ],
    "rera-plotted-developments": [
      "te",
      "hi"
    ],
    "retirement-investment-villa-plots": [
      "te",
      "hi"
    ],
    "rrr-hyderabad-impact": [
      "te",
      "hi"
    ],
    "second-property-investment": [
      "te",
      "hi"
    ],
    "shankarpally-growth-story": [
      "te",
      "hi"
    ],
    "shankarpally-vs-kokapet": [
      "te",
      "hi"
    ],
    "shankarpally-vs-mokila": [
      "te",
      "hi"
    ],
    "site-visit-checklist": [
      "te",
      "hi"
    ],
    "small-budget-plot-investment": [
      "te",
      "hi"
    ],
    "stamp-duty-registration-telangana": [
      "te",
      "hi"
    ],
    "sustainable-villa-design": [
      "te",
      "hi"
    ],
    "tax-benefits-property": [
      "te",
      "hi"
    ],
    "tellapur-kollur-emerging": [
      "te",
      "hi"
    ],
    "vaastu-villa-plots": [
      "te",
      "hi"
    ],
    "verify-land-titles": [
      "te",
      "hi"
    ],
    "villa-design-trends": [
      "te",
      "hi"
    ],
    "villa-plot-investment-guide": [
      "te",
      "hi"
    ],
    "weekend-homes-hyderabad": [
      "te",
      "hi"
    ],
    "why-invest-in-shankarpally": [
      "te",
      "hi"
    ],
    "women-property-ownership": [
      "te",
      "hi"
    ],
    "young-professionals-land-investment": [
      "te",
      "hi"
    ]
  },
  "guides": {
    "construction-guide": [
      "te",
      "hi"
    ],
    "documentation-guide": [
      "te",
      "hi"
    ],
    "dtcp-guide": [
      "te",
      "hi"
    ],
    "hmda-guide": [
      "te",
      "hi"
    ],
    "how-to-buy-villa-plots": [
      "te",
      "hi"
    ],
    "investment-checklist": [
      "te",
      "hi"
    ],
    "legal-verification": [
      "te",
      "hi"
    ],
    "loan-process": [
      "te",
      "hi"
    ],
    "plot-buying-mistakes": [
      "te",
      "hi"
    ],
    "registration-process": [
      "te",
      "hi"
    ],
    "rera-guide": [
      "te",
      "hi"
    ],
    "tax-benefits": [
      "te",
      "hi"
    ]
  },
  "locations": {
    "chevella": [
      "te",
      "hi"
    ],
    "financial-district": [
      "te",
      "hi"
    ],
    "gachibowli": [
      "te",
      "hi"
    ],
    "hyderabad-west": [
      "te",
      "hi"
    ],
    "kokapet": [
      "te",
      "hi"
    ],
    "kollur": [
      "te",
      "hi"
    ],
    "moinabad": [
      "te",
      "hi"
    ],
    "mokila": [
      "te",
      "hi"
    ],
    "narsingi": [
      "te",
      "hi"
    ],
    "orr-corridor": [
      "te",
      "hi"
    ],
    "patancheru": [
      "te",
      "hi"
    ],
    "shankarpally": [
      "te",
      "hi"
    ],
    "tellapur": [
      "te",
      "hi"
    ]
  }
};

/**
 * Dynamic importers, one per overlay. Literal specifiers on purpose: a
 * template literal would make the bundler pull every language's prose into a
 * single context chunk.
 */
export const LOADERS: Record<
  string,
  () => Promise<{ translation: ContentTranslation }>
> = {
  "te:blog:affordability-migration-west": () => import("./te/blog/affordability-migration-west"),
  "te:blog:agricultural-vs-residential-land": () => import("./te/blog/agricultural-vs-residential-land"),
  "te:blog:airport-connectivity-west": () => import("./te/blog/airport-connectivity-west"),
  "te:blog:best-investment-locations-hyderabad": () => import("./te/blog/best-investment-locations-hyderabad"),
  "te:blog:building-villa-on-plot": () => import("./te/blog/building-villa-on-plot"),
  "te:blog:capital-gains-tax-land": () => import("./te/blog/capital-gains-tax-land"),
  "te:blog:chevella-moinabad-belt": () => import("./te/blog/chevella-moinabad-belt"),
  "te:blog:clubhouse-lifestyle": () => import("./te/blog/clubhouse-lifestyle"),
  "te:blog:construction-cost-planning": () => import("./te/blog/construction-cost-planning"),
  "te:blog:down-payment-planning": () => import("./te/blog/down-payment-planning"),
  "te:blog:east-vs-west-hyderabad": () => import("./te/blog/east-vs-west-hyderabad"),
  "te:blog:encumbrance-certificate-guide": () => import("./te/blog/encumbrance-certificate-guide"),
  "te:blog:financial-district-spillover": () => import("./te/blog/financial-district-spillover"),
  "te:blog:first-time-plot-buyer": () => import("./te/blog/first-time-plot-buyer"),
  "te:blog:future-city-vision": () => import("./te/blog/future-city-vision"),
  "te:blog:future-of-hyderabad-west": () => import("./te/blog/future-of-hyderabad-west"),
  "te:blog:gated-community-living": () => import("./te/blog/gated-community-living"),
  "te:blog:gst-real-estate": () => import("./te/blog/gst-real-estate"),
  "te:blog:hmda-vs-dtcp": () => import("./te/blog/hmda-vs-dtcp"),
  "te:blog:hyderabad-real-estate-trends": () => import("./te/blog/hyderabad-real-estate-trends"),
  "te:blog:hyderabad-vs-bangalore-realty": () => import("./te/blog/hyderabad-vs-bangalore-realty"),
  "te:blog:hyderabad-west-schools": () => import("./te/blog/hyderabad-west-schools"),
  "te:blog:iit-hyderabad-kandi-effect": () => import("./te/blog/iit-hyderabad-kandi-effect"),
  "te:blog:industrial-corridors-hyderabad": () => import("./te/blog/industrial-corridors-hyderabad"),
  "te:blog:infrastructure-projects-hyderabad": () => import("./te/blog/infrastructure-projects-hyderabad"),
  "te:blog:it-sector-hyderabad-realty": () => import("./te/blog/it-sector-hyderabad-realty"),
  "te:blog:joint-family-property-investment": () => import("./te/blog/joint-family-property-investment"),
  "te:blog:kokapet-neopolis-effect": () => import("./te/blog/kokapet-neopolis-effect"),
  "te:blog:land-appreciation-hyderabad-west": () => import("./te/blog/land-appreciation-hyderabad-west"),
  "te:blog:land-banking-strategy": () => import("./te/blog/land-banking-strategy"),
  "te:blog:land-price-drivers": () => import("./te/blog/land-price-drivers"),
  "te:blog:luxury-living-west-hyderabad": () => import("./te/blog/luxury-living-west-hyderabad"),
  "te:blog:market-cycles-land": () => import("./te/blog/market-cycles-land"),
  "te:blog:metro-expansion-west": () => import("./te/blog/metro-expansion-west"),
  "te:blog:mmts-shankarpally-connectivity": () => import("./te/blog/mmts-shankarpally-connectivity"),
  "te:blog:mokila-villa-corridor": () => import("./te/blog/mokila-villa-corridor"),
  "te:blog:negotiating-plot-purchase": () => import("./te/blog/negotiating-plot-purchase"),
  "te:blog:nri-guide-plot-investment": () => import("./te/blog/nri-guide-plot-investment"),
  "te:blog:orr-exit3-corridor": () => import("./te/blog/orr-exit3-corridor"),
  "te:blog:orr-growth-story": () => import("./te/blog/orr-growth-story"),
  "te:blog:patancheru-industrial-corridor": () => import("./te/blog/patancheru-industrial-corridor"),
  "te:blog:plot-buying-mistakes-stories": () => import("./te/blog/plot-buying-mistakes-stories"),
  "te:blog:plot-loan-vs-home-loan": () => import("./te/blog/plot-loan-vs-home-loan"),
  "te:blog:plots-vs-apartments": () => import("./te/blog/plots-vs-apartments"),
  "te:blog:plotted-development-boom": () => import("./te/blog/plotted-development-boom"),
  "te:blog:portfolio-diversification-real-estate": () => import("./te/blog/portfolio-diversification-real-estate"),
  "te:blog:property-mutation-telangana": () => import("./te/blog/property-mutation-telangana"),
  "te:blog:reading-layout-plans": () => import("./te/blog/reading-layout-plans"),
  "te:blog:real-estate-vs-gold-vs-equity": () => import("./te/blog/real-estate-vs-gold-vs-equity"),
  "te:blog:regional-ring-road-progress": () => import("./te/blog/regional-ring-road-progress"),
  "te:blog:rental-yield-vs-appreciation": () => import("./te/blog/rental-yield-vs-appreciation"),
  "te:blog:rera-plotted-developments": () => import("./te/blog/rera-plotted-developments"),
  "te:blog:retirement-investment-villa-plots": () => import("./te/blog/retirement-investment-villa-plots"),
  "te:blog:rrr-hyderabad-impact": () => import("./te/blog/rrr-hyderabad-impact"),
  "te:blog:second-property-investment": () => import("./te/blog/second-property-investment"),
  "te:blog:shankarpally-growth-story": () => import("./te/blog/shankarpally-growth-story"),
  "te:blog:shankarpally-vs-kokapet": () => import("./te/blog/shankarpally-vs-kokapet"),
  "te:blog:shankarpally-vs-mokila": () => import("./te/blog/shankarpally-vs-mokila"),
  "te:blog:site-visit-checklist": () => import("./te/blog/site-visit-checklist"),
  "te:blog:small-budget-plot-investment": () => import("./te/blog/small-budget-plot-investment"),
  "te:blog:stamp-duty-registration-telangana": () => import("./te/blog/stamp-duty-registration-telangana"),
  "te:blog:sustainable-villa-design": () => import("./te/blog/sustainable-villa-design"),
  "te:blog:tax-benefits-property": () => import("./te/blog/tax-benefits-property"),
  "te:blog:tellapur-kollur-emerging": () => import("./te/blog/tellapur-kollur-emerging"),
  "te:blog:vaastu-villa-plots": () => import("./te/blog/vaastu-villa-plots"),
  "te:blog:verify-land-titles": () => import("./te/blog/verify-land-titles"),
  "te:blog:villa-design-trends": () => import("./te/blog/villa-design-trends"),
  "te:blog:villa-plot-investment-guide": () => import("./te/blog/villa-plot-investment-guide"),
  "te:blog:weekend-homes-hyderabad": () => import("./te/blog/weekend-homes-hyderabad"),
  "te:blog:why-invest-in-shankarpally": () => import("./te/blog/why-invest-in-shankarpally"),
  "te:blog:women-property-ownership": () => import("./te/blog/women-property-ownership"),
  "te:blog:young-professionals-land-investment": () => import("./te/blog/young-professionals-land-investment"),
  "te:guides:construction-guide": () => import("./te/guides/construction-guide"),
  "te:guides:documentation-guide": () => import("./te/guides/documentation-guide"),
  "te:guides:dtcp-guide": () => import("./te/guides/dtcp-guide"),
  "te:guides:hmda-guide": () => import("./te/guides/hmda-guide"),
  "te:guides:how-to-buy-villa-plots": () => import("./te/guides/how-to-buy-villa-plots"),
  "te:guides:investment-checklist": () => import("./te/guides/investment-checklist"),
  "te:guides:legal-verification": () => import("./te/guides/legal-verification"),
  "te:guides:loan-process": () => import("./te/guides/loan-process"),
  "te:guides:plot-buying-mistakes": () => import("./te/guides/plot-buying-mistakes"),
  "te:guides:registration-process": () => import("./te/guides/registration-process"),
  "te:guides:rera-guide": () => import("./te/guides/rera-guide"),
  "te:guides:tax-benefits": () => import("./te/guides/tax-benefits"),
  "te:locations:chevella": () => import("./te/locations/chevella"),
  "te:locations:financial-district": () => import("./te/locations/financial-district"),
  "te:locations:gachibowli": () => import("./te/locations/gachibowli"),
  "te:locations:hyderabad-west": () => import("./te/locations/hyderabad-west"),
  "te:locations:kokapet": () => import("./te/locations/kokapet"),
  "te:locations:kollur": () => import("./te/locations/kollur"),
  "te:locations:moinabad": () => import("./te/locations/moinabad"),
  "te:locations:mokila": () => import("./te/locations/mokila"),
  "te:locations:narsingi": () => import("./te/locations/narsingi"),
  "te:locations:orr-corridor": () => import("./te/locations/orr-corridor"),
  "te:locations:patancheru": () => import("./te/locations/patancheru"),
  "te:locations:shankarpally": () => import("./te/locations/shankarpally"),
  "te:locations:tellapur": () => import("./te/locations/tellapur"),
  "hi:blog:affordability-migration-west": () => import("./hi/blog/affordability-migration-west"),
  "hi:blog:agricultural-vs-residential-land": () => import("./hi/blog/agricultural-vs-residential-land"),
  "hi:blog:airport-connectivity-west": () => import("./hi/blog/airport-connectivity-west"),
  "hi:blog:best-investment-locations-hyderabad": () => import("./hi/blog/best-investment-locations-hyderabad"),
  "hi:blog:building-villa-on-plot": () => import("./hi/blog/building-villa-on-plot"),
  "hi:blog:capital-gains-tax-land": () => import("./hi/blog/capital-gains-tax-land"),
  "hi:blog:chevella-moinabad-belt": () => import("./hi/blog/chevella-moinabad-belt"),
  "hi:blog:clubhouse-lifestyle": () => import("./hi/blog/clubhouse-lifestyle"),
  "hi:blog:construction-cost-planning": () => import("./hi/blog/construction-cost-planning"),
  "hi:blog:down-payment-planning": () => import("./hi/blog/down-payment-planning"),
  "hi:blog:east-vs-west-hyderabad": () => import("./hi/blog/east-vs-west-hyderabad"),
  "hi:blog:encumbrance-certificate-guide": () => import("./hi/blog/encumbrance-certificate-guide"),
  "hi:blog:financial-district-spillover": () => import("./hi/blog/financial-district-spillover"),
  "hi:blog:first-time-plot-buyer": () => import("./hi/blog/first-time-plot-buyer"),
  "hi:blog:future-city-vision": () => import("./hi/blog/future-city-vision"),
  "hi:blog:future-of-hyderabad-west": () => import("./hi/blog/future-of-hyderabad-west"),
  "hi:blog:gated-community-living": () => import("./hi/blog/gated-community-living"),
  "hi:blog:gst-real-estate": () => import("./hi/blog/gst-real-estate"),
  "hi:blog:hmda-vs-dtcp": () => import("./hi/blog/hmda-vs-dtcp"),
  "hi:blog:hyderabad-real-estate-trends": () => import("./hi/blog/hyderabad-real-estate-trends"),
  "hi:blog:hyderabad-vs-bangalore-realty": () => import("./hi/blog/hyderabad-vs-bangalore-realty"),
  "hi:blog:hyderabad-west-schools": () => import("./hi/blog/hyderabad-west-schools"),
  "hi:blog:iit-hyderabad-kandi-effect": () => import("./hi/blog/iit-hyderabad-kandi-effect"),
  "hi:blog:industrial-corridors-hyderabad": () => import("./hi/blog/industrial-corridors-hyderabad"),
  "hi:blog:infrastructure-projects-hyderabad": () => import("./hi/blog/infrastructure-projects-hyderabad"),
  "hi:blog:it-sector-hyderabad-realty": () => import("./hi/blog/it-sector-hyderabad-realty"),
  "hi:blog:joint-family-property-investment": () => import("./hi/blog/joint-family-property-investment"),
  "hi:blog:kokapet-neopolis-effect": () => import("./hi/blog/kokapet-neopolis-effect"),
  "hi:blog:land-appreciation-hyderabad-west": () => import("./hi/blog/land-appreciation-hyderabad-west"),
  "hi:blog:land-banking-strategy": () => import("./hi/blog/land-banking-strategy"),
  "hi:blog:land-price-drivers": () => import("./hi/blog/land-price-drivers"),
  "hi:blog:luxury-living-west-hyderabad": () => import("./hi/blog/luxury-living-west-hyderabad"),
  "hi:blog:market-cycles-land": () => import("./hi/blog/market-cycles-land"),
  "hi:blog:metro-expansion-west": () => import("./hi/blog/metro-expansion-west"),
  "hi:blog:mmts-shankarpally-connectivity": () => import("./hi/blog/mmts-shankarpally-connectivity"),
  "hi:blog:mokila-villa-corridor": () => import("./hi/blog/mokila-villa-corridor"),
  "hi:blog:negotiating-plot-purchase": () => import("./hi/blog/negotiating-plot-purchase"),
  "hi:blog:nri-guide-plot-investment": () => import("./hi/blog/nri-guide-plot-investment"),
  "hi:blog:orr-exit3-corridor": () => import("./hi/blog/orr-exit3-corridor"),
  "hi:blog:orr-growth-story": () => import("./hi/blog/orr-growth-story"),
  "hi:blog:patancheru-industrial-corridor": () => import("./hi/blog/patancheru-industrial-corridor"),
  "hi:blog:plot-buying-mistakes-stories": () => import("./hi/blog/plot-buying-mistakes-stories"),
  "hi:blog:plot-loan-vs-home-loan": () => import("./hi/blog/plot-loan-vs-home-loan"),
  "hi:blog:plots-vs-apartments": () => import("./hi/blog/plots-vs-apartments"),
  "hi:blog:plotted-development-boom": () => import("./hi/blog/plotted-development-boom"),
  "hi:blog:portfolio-diversification-real-estate": () => import("./hi/blog/portfolio-diversification-real-estate"),
  "hi:blog:property-mutation-telangana": () => import("./hi/blog/property-mutation-telangana"),
  "hi:blog:reading-layout-plans": () => import("./hi/blog/reading-layout-plans"),
  "hi:blog:real-estate-vs-gold-vs-equity": () => import("./hi/blog/real-estate-vs-gold-vs-equity"),
  "hi:blog:regional-ring-road-progress": () => import("./hi/blog/regional-ring-road-progress"),
  "hi:blog:rental-yield-vs-appreciation": () => import("./hi/blog/rental-yield-vs-appreciation"),
  "hi:blog:rera-plotted-developments": () => import("./hi/blog/rera-plotted-developments"),
  "hi:blog:retirement-investment-villa-plots": () => import("./hi/blog/retirement-investment-villa-plots"),
  "hi:blog:rrr-hyderabad-impact": () => import("./hi/blog/rrr-hyderabad-impact"),
  "hi:blog:second-property-investment": () => import("./hi/blog/second-property-investment"),
  "hi:blog:shankarpally-growth-story": () => import("./hi/blog/shankarpally-growth-story"),
  "hi:blog:shankarpally-vs-kokapet": () => import("./hi/blog/shankarpally-vs-kokapet"),
  "hi:blog:shankarpally-vs-mokila": () => import("./hi/blog/shankarpally-vs-mokila"),
  "hi:blog:site-visit-checklist": () => import("./hi/blog/site-visit-checklist"),
  "hi:blog:small-budget-plot-investment": () => import("./hi/blog/small-budget-plot-investment"),
  "hi:blog:stamp-duty-registration-telangana": () => import("./hi/blog/stamp-duty-registration-telangana"),
  "hi:blog:sustainable-villa-design": () => import("./hi/blog/sustainable-villa-design"),
  "hi:blog:tax-benefits-property": () => import("./hi/blog/tax-benefits-property"),
  "hi:blog:tellapur-kollur-emerging": () => import("./hi/blog/tellapur-kollur-emerging"),
  "hi:blog:vaastu-villa-plots": () => import("./hi/blog/vaastu-villa-plots"),
  "hi:blog:verify-land-titles": () => import("./hi/blog/verify-land-titles"),
  "hi:blog:villa-design-trends": () => import("./hi/blog/villa-design-trends"),
  "hi:blog:villa-plot-investment-guide": () => import("./hi/blog/villa-plot-investment-guide"),
  "hi:blog:weekend-homes-hyderabad": () => import("./hi/blog/weekend-homes-hyderabad"),
  "hi:blog:why-invest-in-shankarpally": () => import("./hi/blog/why-invest-in-shankarpally"),
  "hi:blog:women-property-ownership": () => import("./hi/blog/women-property-ownership"),
  "hi:blog:young-professionals-land-investment": () => import("./hi/blog/young-professionals-land-investment"),
  "hi:guides:construction-guide": () => import("./hi/guides/construction-guide"),
  "hi:guides:documentation-guide": () => import("./hi/guides/documentation-guide"),
  "hi:guides:dtcp-guide": () => import("./hi/guides/dtcp-guide"),
  "hi:guides:hmda-guide": () => import("./hi/guides/hmda-guide"),
  "hi:guides:how-to-buy-villa-plots": () => import("./hi/guides/how-to-buy-villa-plots"),
  "hi:guides:investment-checklist": () => import("./hi/guides/investment-checklist"),
  "hi:guides:legal-verification": () => import("./hi/guides/legal-verification"),
  "hi:guides:loan-process": () => import("./hi/guides/loan-process"),
  "hi:guides:plot-buying-mistakes": () => import("./hi/guides/plot-buying-mistakes"),
  "hi:guides:registration-process": () => import("./hi/guides/registration-process"),
  "hi:guides:rera-guide": () => import("./hi/guides/rera-guide"),
  "hi:guides:tax-benefits": () => import("./hi/guides/tax-benefits"),
  "hi:locations:chevella": () => import("./hi/locations/chevella"),
  "hi:locations:financial-district": () => import("./hi/locations/financial-district"),
  "hi:locations:gachibowli": () => import("./hi/locations/gachibowli"),
  "hi:locations:hyderabad-west": () => import("./hi/locations/hyderabad-west"),
  "hi:locations:kokapet": () => import("./hi/locations/kokapet"),
  "hi:locations:kollur": () => import("./hi/locations/kollur"),
  "hi:locations:moinabad": () => import("./hi/locations/moinabad"),
  "hi:locations:mokila": () => import("./hi/locations/mokila"),
  "hi:locations:narsingi": () => import("./hi/locations/narsingi"),
  "hi:locations:orr-corridor": () => import("./hi/locations/orr-corridor"),
  "hi:locations:patancheru": () => import("./hi/locations/patancheru"),
  "hi:locations:shankarpally": () => import("./hi/locations/shankarpally"),
  "hi:locations:tellapur": () => import("./hi/locations/tellapur"),
};

/**
 * Card translations — title, summary and metadata for a listing page.
 *
 * Keyed `<locale>:<kind>`, one module per collection rather than one per
 * slug, because a listing page needs all of them at once.
 */
export const CARD_LOADERS: Record<
  string,
  () => Promise<{ cards: Record<string, CardTranslation> }>
> = {
  "te:blog": () => import("./te/cards/blog"),
  "te:guides": () => import("./te/cards/guides"),
  "te:locations": () => import("./te/cards/locations"),
  "hi:blog": () => import("./hi/cards/blog"),
  "hi:guides": () => import("./hi/cards/guides"),
  "hi:locations": () => import("./hi/cards/locations"),
};
