// AUTO-GENERATED by scripts/gen-content-index.mjs — do not edit by hand.
import type { LocationContent } from "@/lib/types";
import { location as m0 } from "./chevella";
import { location as m1 } from "./financial-district";
import { location as m2 } from "./gachibowli";
import { location as m3 } from "./hyderabad-west";
import { location as m4 } from "./kokapet";
import { location as m5 } from "./kollur";
import { location as m6 } from "./moinabad";
import { location as m7 } from "./mokila";
import { location as m8 } from "./narsingi";
import { location as m9 } from "./orr-corridor";
import { location as m10 } from "./patancheru";
import { location as m11 } from "./shankarpally";
import { location as m12 } from "./tellapur";

export const locations: LocationContent[] = [m0, m1, m2, m3, m4, m5, m6, m7, m8, m9, m10, m11, m12];

export function getBySlug(slug: string): LocationContent | undefined {
  return locations.find((x) => x.slug === slug);
}
