// AUTO-GENERATED by scripts/gen-content-index.mjs — do not edit by hand.
import type { GuideContent } from "@/lib/types";
import { guide as m0 } from "./construction-guide";
import { guide as m1 } from "./documentation-guide";
import { guide as m2 } from "./dtcp-guide";
import { guide as m3 } from "./hmda-guide";
import { guide as m4 } from "./how-to-buy-villa-plots";
import { guide as m5 } from "./investment-checklist";
import { guide as m6 } from "./legal-verification";
import { guide as m7 } from "./loan-process";
import { guide as m8 } from "./plot-buying-mistakes";
import { guide as m9 } from "./registration-process";
import { guide as m10 } from "./rera-guide";
import { guide as m11 } from "./tax-benefits";

export const guides: GuideContent[] = [m0, m1, m2, m3, m4, m5, m6, m7, m8, m9, m10, m11];

export function getBySlug(slug: string): GuideContent | undefined {
  return guides.find((x) => x.slug === slug);
}
